spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8071/}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#  health:
#    readiness-state:
#      enabled: true
#    liveness-state:
#      enabled: true

  info:
    env:
      enabled: true

  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true

info:
  app:
    name: "gatewayserver"
    description: "desc for gateway"