spring:
  application:
    name: discover-server

server:
  port: 8761
  healthcheck:
    test: "curl --fail --silent localhost:8071/actuator/health/readiness "
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 10s

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
