spring:
  application:
    name: ms-one
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8071/}"

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  info:
    env:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "ms-one"
    description: "ms-one service"