spring:
  application:
    name: ms-two
  config:
    import: "optional:configserver:${CONFIG_SERVER:http://localhost:8071/}"

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:

management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "ms-two"
    description: "ms-two service"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"