spring:
  application:
    name: "config-server"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/prateek-nst/spring-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
