spring:
  application:
    name: "config-server"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/prateek-nst/spring-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  health:
#    readiness-state:
#      enabled: true
#    liveness-state:check port ls
#      enabled: false

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8071
  healthcheck:
    test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 10s

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"